[".local/bin/tmux-sessionizer"]
type = "file"
url = "https://raw.githubusercontent.com/ThePrimeagen/tmux-sessionizer/7edf8211e36368c29ffc0d2c6d5d2d350b4d729b/tmux-sessionizer"
executable = true
checksum.sha256 = "9242b732dd46faddeaf41ebed5e27058e9d140761908ab16b61cd6ff3b9b6b1e"
