# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# TMUX CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

source-file ~/.config/tmux/conf.d/00-environment.tmux
source-file ~/.config/tmux/conf.d/10-options.tmux
source-file ~/.config/tmux/conf.d/20-keybindings.tmux
source-file ~/.config/tmux/conf.d/30-mouse.tmux
source-file ~/.config/tmux/conf.d/40-plugins.tmux

run-shell "~/.config/tmux/plugins/tpm/tpm >/dev/null 2>&1; tmux source-file ~/.config/tmux/conf.d/90-after-plugins.tmux"
