# ─────────────────────────────────────────────────────────────────────────────
# Plugin-After Overrides
# ─────────────────────────────────────────────────────────────────────────────

bind BSpace switch-client -l

# Keep the viewport anchored after keyboard copy actions.
unbind -T copy-mode-vi M-y
unbind -T copy-mode M-y

bind -T copy-mode-vi Enter send-keys -X copy-pipe-no-clear
bind -T copy-mode-vi ! send-keys -X copy-pipe-no-clear "tr -d '\n' | xsel -i --clipboard"
bind -T copy-mode-vi y send-keys -X copy-pipe-no-clear "xsel -i --clipboard"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "xsel -i --clipboard"
bind -T copy-mode-vi DoubleClick1Pane select-pane \; send-keys -X select-word \; run-shell -d 0.3 \; send-keys -X copy-pipe
bind -T copy-mode-vi TripleClick1Pane select-pane \; send-keys -X select-line \; run-shell -d 0.3 \; send-keys -X copy-pipe
bind -T copy-mode-vi C-j send-keys -X copy-pipe-no-clear

bind -T copy-mode ! send-keys -X copy-pipe-no-clear "tr -d '\n' | xsel -i --clipboard"
bind -T copy-mode y send-keys -X copy-pipe-no-clear "xsel -i --clipboard"
bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe "xsel -i --clipboard"
bind -T copy-mode DoubleClick1Pane select-pane \; send-keys -X select-word \; run-shell -d 0.3 \; send-keys -X copy-pipe
bind -T copy-mode TripleClick1Pane select-pane \; send-keys -X select-line \; run-shell -d 0.3 \; send-keys -X copy-pipe
bind -T copy-mode M-w send-keys -X copy-pipe-no-clear
bind -T copy-mode C-k send-keys -X copy-pipe-end-of-line
bind -T copy-mode C-w send-keys -X copy-pipe-no-clear

bind -T root DoubleClick1Pane select-pane -t = \; if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" "send-keys -M" "copy-mode -H \\; send-keys -X select-word \\; run-shell -d 0.3 \\; send-keys -X copy-pipe"
bind -T root TripleClick1Pane select-pane -t = \; if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" "send-keys -M" "copy-mode -H \\; send-keys -X select-line \\; run-shell -d 0.3 \\; send-keys -X copy-pipe"
