[env]
TERM = "xterm-256color"


[general]
import = ["./dracula.toml"]


[window]
opacity = 0.6
decorations = "none"

[window.dimensions]
columns = 150
lines = 30


[font]
size = 11.0
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }


[cursor]
vi_mode_style.shape = "Block"


[mouse]
hide_when_typing = true

[hints]
enabled = [
  { regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\\u0000-\\u001F\\u007F-\\u009F<>\"\\s{-}\\^⟨⟩`]+", hyperlinks = true, command = "xdg-open", post_processing = true, mouse = { enabled = true, mods = "None" }, binding = { key = "U", mods = "Control|Shift" } }
]
