# Terminal Configuration
[terminal.shell]
program = "/usr/bin/tmux"                # Use tmux as the default shell
args = ["new-session"]                   # Always create new session

# Environment Variables
[env]
TERM = "xterm-256color"                  # Set terminal type for proper color support

# General Settings
[general]
import = ["./dracula.toml"]              # Import Dracula color theme

# Scrolling Configuration
[scrolling]
history = 10000                          # Increase scroll history buffer
multiplier = 3                           # Faster scrolling speed

# Window Configuration
[window]
startup_mode = "Maximized"               # Start in maximized mode
opacity = 0.8                            # Set window transparency (60% opaque)

[window.dimensions]
columns = 120                            # Initial window width in columns
lines = 30                               # Initial window height in lines

# Font Configuration
[font]
size = 11.0                              # Font size in points
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

# Color Configuration
[colors]
draw_bold_text_with_bright_colors = true # Bold text bright color

# Cursor Configuration
[cursor]
vi_mode_style.shape = "Block"            # Use block cursor in vi mode

# Mouse Configuration
[mouse]
hide_when_typing = true                  # Hide mouse cursor when typing

# URL Hints Configuration
[hints]
enabled = [
  { regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\\u0000-\\u001F\\u007F-\\u009F<>\"\\s{-}\\^⟨⟩`]+", hyperlinks = true, command = "xdg-open", post_processing = true, mouse = { enabled = true, mods = "None" }, binding = { key = "U", mods = "Control|Shift" } }
]                                        # Enable clickable links, Ctrl+Shift+U to open
