# Terminal Configuration
[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session"]

# Environment Variables
[env]
TERM = "xterm-256color"

# General Settings
[general]
import = ["./dracula.toml"]

# Scrolling Configuration
[scrolling]
history = 10000
multiplier = 3

# Window Configuration
[window]
startup_mode = "Maximized"
opacity = 0.8
decorations = "None"

[window.dimensions]
columns = 120
lines = 30

# Font Configuration
[font]
size = 11.0
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }

# Color Configuration
[colors]
draw_bold_text_with_bright_colors = true

# Cursor Configuration
[cursor]
vi_mode_style.shape = "Block"

# Mouse Configuration
[mouse]
hide_when_typing = true

# URL Hints Configuration
[hints]
enabled = [
  { regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\\u0000-\\u001F\\u007F-\\u009F<>\"\\s{-}\\^⟨⟩`]+", hyperlinks = true, command = "xdg-open", post_processing = true, mouse = { enabled = true, mods = "None" }, binding = { key = "U", mods = "Control|Shift" } }
]
