# ╭─────────────────────────────────────────────────────────╮
# │                    Yazi Theme Config                    │
# ╰─────────────────────────────────────────────────────────╯

# ═══════════════════════════════════════════════════════════
#  Theme Selection
# ═══════════════════════════════════════════════════════════

[flavor]
dark = "dracula"
light = "dracula"
